name: alphawet
description: AlphaWet Flutter UI for importing .aw configs, building runtime JSON, and launching secure runtimes.
publish_to: 'none'
version: 2.3.8+238

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.10
  cryptography: ^2.7.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/common/logo/
    - assets/xray/common/
    - assets/xray/desktop/
